### PR TITLE
feat: video sorting by latest, popular and oldest

### PR DESCRIPTION
**Pull request by Jubair70**
This pr will close https://github.com/foyzulkarim/mern-video-streaming/issues/30

- Users can sort the videos into three categories: Latest, Popular, and Oldest.
- Although the issue states the requirement `sort by view count, then newer first`, I have implemented it as `Popular`
- `Popular` category sort the videos by views count first. if the view count equals then it will sort by date and time in descending order.
- When the videos list renders on start, it will sort the videos under the `Popular` category by default.
Screenshot 2023-07-28 at 11 50 54 AM

### CODE REVIEW

**Comment by foyzulkarim** [comment]
thanks for the pull request brother. I would like to request you to allow me some time (2 weeks) to complete my current refactoring on the server side (making genric repo thing). then i can accept this PR. Thanks 🙏

**Comment by foyzulkarim** [comment]
@Jubair70  please have a look
https://github.com/foyzulkarim/mern-video-streaming/issues/51

**Comment by foyzulkarim** [comment]
this pr has conflicts.

**Comment by foyzulkarim** [comment]
when you complete your changes, please use the label `ready for review`

**Comment by foyzulkarim** [comment]
this feature should contain the implementation of server side as well.

when you complete your changes, please use the label `ready for review`

**Comment by Jubair70** [comment]
Hello @foyzulkarim vai,
I don't think I have enough permission to change the label.
Thanks!

**Comment by foyzulkarim** [comment]
Thanks for your hard work brother @Jubair70  . Please have a look on this issue and you can start working on this. 
https://github.com/foyzulkarim/mern-video-streaming/issues/51  

You can close this pull request and start fresh from that issue or you can keep updating this pull request if you want to.
Please let me know if you have any question.

**Comment by foyzulkarim** [comment]
Looks good for now. actual implementation of sorting will be handled in another ticket.

#51

**Pull request merged**
