### PR TITLE
show durations and published date on the video thumbnails

### LINKED ISSUE #28: show durations on the video thumbnails

### LINKED ISSUE #29: show published date using date library

### PR DESCRIPTION
**Pull request by aninda052**
This pr will close multiple issues -

close #28 
* add `ffprobe` package for getting video metadata
* add `@ffprobe-installer/ffprobe` for platform independent binary installer
* add `durations` filed in `videos` collection to store video durations in second
* get video `durations` in seconds using `ffprobe` and store that while storing video info in db
* use `react-moment` package to format(`HH:mm:ss`) video `durations`.  

close #29 
* shows `recordingDate` as published date in video thumbnails.
* use `react-moment` package to format(`DD/MM/yyyy`)  `recordingDate`.

### CODE REVIEW

**Comment by foyzulkarim** [comment]
thanks for the pull request brother. I would like to request you to allow me some time (2 weeks) to complete my current refactoring on the server side (making genric repo thing). then i can accept this PR. Thanks 🙏

**Comment by foyzulkarim** [comment]
@aninda052 please have a look
https://github.com/foyzulkarim/mern-video-streaming/issues/51

**Comment by foyzulkarim** [comment]
@aninda052  please resolve the conflicts.. thanks 👍

**Comment by aninda052** [comment]
> @aninda052 please resolve the conflicts.. thanks +1

@foyzulkarim conflict resolve

**Comment by foyzulkarim** [comment]
what is the difference between this work and #47 ?

either use different code in different PR, or close either of the PR please.

**Comment by aninda052** [comment]
closing this pr as i already merge  [feature/video-durations](https://github.com/aninda052/mern-video-streaming/tree/feature/video-durations) into [feature/update-video-status](https://github.com/aninda052/mern-video-streaming/tree/feature/update-video-status)

**Pull request closed without merging**
