### PR TITLE
client hosted on vercel

### PR DESCRIPTION
**Pull request by mohammadShamimReza**
I just host the client to vercel here is the link: https://mern-video-streaming.vercel.app/videos

### CODE REVIEW

**Comment by foyzulkarim** [comment]
Thanks for your PR brother, but how will this pull request help the repository to automatically deploy to vercel?

**Comment by mohammadShamimReza** [comment]
sorry brother, I just wanna inform you that i deploy the client to vercel and give the link. 

I read vercel docs that if any code push in github (main) it will automatically deploy again.

if I have done the wrong thing please tell me. I will make it correct

**Comment by foyzulkarim** [comment]
Thanks for the reply.
What I want to know is, if there is any config thing which we can add to the github repository?
So that i will just add my Tokens to that config file and it will automatically do the deployment to vercel. 

If there is nothing like this type of config file, then you can add some explanation about your findings.

**Comment by mohammadShamimReza** [comment]
Thanks,

I think the answer is here: https://vercel.com/docs/concepts/deployments/git#deploying-forks-of-public-git-repositories 
                                          https://vercel.com/docs/concepts/deployments/git/vercel-for-github#deployment-authorizations-for-forks

**Comment by foyzulkarim** [comment]
Brother, taking the lead means providing guideline and summary what can be done next. If possible, write some note why you think adding a vercel config is `possible` or `not possible` so that we can come to a conclusion.
Sending the link is not a good way of communication because I don't have any context about vercel deployment via github repository.

**Comment by foyzulkarim** [comment]
when you complete your changes, please use the label `ready for review`

**Comment by mohammadShamimReza** [comment]
Ok, the thing is vercel deployment work automatically when code is pushed in github. if the project is deployed through github. Means 
When a public repository is forked, commits from it will usually deploy automatically. However, when you receive a pull request from a fork of your repository that includes a change to the [vercel.json] file or the project has [Environment Variables], Vercel will require authorization from you or a [Team Member] to deploy the pull request. This is a security measure that protects you from leaking sensitive project information. A link to authorize the Deployment will be posted as a comment on the Pull Request.

The authorization step will be skipped if the commit author is already a [Team Member] on Vercel.

**Comment by foyzulkarim** [comment]
So, we can close this issue as it it not feasible and not important for now. 
Thanks @mohammadShamimReza brother for the effort.

**Pull request closed without merging**
