### PR TITLE
video edit page

### LINKED ISSUE #55: (Client) Implement Video Edit page
When we click on the `Edit` link/button, we will navigated to a new page and load all of the video information in  the page.

No need to `UPDATE` the property in this ticket.

### PR DESCRIPTION
**Pull request by aninda052**
This will close #55 

* add new page for `video update` 
* modify server side `video validation schema`
* show `recordingDate` in `video list` page
* add `update` action in `video list` page
*  in `video list` page navigate `New Video` button to `upload video` page

### CODE REVIEW

**Comment by foyzulkarim** [comment]
Hi @aninda052 
thanks for the awesome work. 
Let's not over-use our upload page and keep it as it is.
Can you create a new `VideoEditPage` to edit the text values (NOT the uploaded video itself) please?

Also, take the latest code from main branch. Update the List page and add a Edit button in the actions (keep the Delete action but remove the other actions).

Otherwise all code seems good.

**Comment by aninda052** [comment]
> Can you create a new `VideoEditPage` to edit the text values (NOT the uploaded video itself) please?

@foyzulkarim vai, the reason behind the re-use of `upload` page is to not use duplicate codes. Codes for  `upload`  and `edit` page will be almost same. Also if we use separate file, in future if we have to add a new field in 'upload' page, we also have to do the same things for `edit` page.
Is it possible to tell me in details why we want to keep separate files ?

**Comment by foyzulkarim** [comment]
Good point. I like your argument.
But it is most likely we will not be showing all fields in the upload page. And we will not edit all fields as well. Also, if we create different logics while uploading and editing, then it will be too much complicated to manage in a single page. 
For now, it seems duplicate, but in the long run, it is not that much duplicate.

**Comment by foyzulkarim** [comment]
If the fields are same, then I would like to create a common `Form` for these two, but create two different page (wrapper type component) which will have their own separate logics. 
For example: if you don't want to give permission to everyone to edit, then the Edit page will be having that logic. 
This is a fine contradiction/balance between SRP and DYI principles. 🙂

**Comment by aninda052** [comment]
> If the fields are same, then I would like to create a common `Form` for these two, but create two different page (wrapper type component) which will have their own separate logics.

Thank you vai for this suggestion. i'll follow this in future <3 

btw, i've pushed my updated code and update pull description.

**Review by foyzulkarim — APPROVED** [review]
🥳

**Pull request merged**
